### ISSUE TITLE
Entropy theme requires vcprompt

### ISSUE THREAD

**Issue by timfallmk** [justinmayer/tackle#10]
Looks like the entropy theme requires `vcprompt` to be installed. Could you document that requirement, or better yet, since it isn't maintained anymore, switch to a fork that is?

Much thanks!

**Comment by justinmayer** [comment]
> Looks like the entropy theme requires vcprompt to be installed. Could you document that requirement, or better yet, since it isn't maintained anymore, switch to a fork that is?

That's [already documented](https://github.com/justinmayer/tackle/tree/master/themes/entropy#requirements), is it not?

And what gives you the impression that `vcprompt` is unmaintained?

**Comment by timfallmk** [comment]
I suppose it's documented for Mac, but it might be worth mentioning that on this page as well, since there's no obvious error (other than a missing python lib warning).

Also, the original project is not under development anymore https://github.com/djl/vcprompt

**Comment by justinmayer** [comment]
I think you are a bit confused. My Entropy theme was never intended use that project, which is a much slower, defunct Python re-implementation of the original C-based `vcprompt` — the latter is actually still maintained. If you were to follow the `vcprompt` link in Entropy's README, you would see that.

If you would like to submit a pull request that checks for the existence of a `vcprompt` executable on the user's PATH, providing a more user-friendly error message if it is not found, that would be a welcome improvement.
