### ISSUE TITLE
Join Wahoo?

### ISSUE THREAD

**Issue by bucaran** [justinmayer/tackle#12]
We are still relatively new in town, and just getting started, but we are highly motivated :smile:  

I think a lot of these functions could be turned into a handful of Wahoo plugins or maybe some could be even make it to core. Of course, your project is useful just as it is and I am _not_ asking to merge, but it would be great if you could lend us a hand over at [Wahoo](https://github.com/fish-shell/wahoo/). If you have no idea what I am talking about, here is a little [FAQ](https://github.com/fish-shell/wahoo/blob/master/FAQ.md) too.

:+1:

**Comment by justinmayer** [comment]
I'll take a look. Thanks.
