### ISSUE TITLE
__vfsupport_setup_autocomplete is not executed automatically

### ISSUE THREAD

**Issue by doxxx** [justinmayer/tackle#14]
I'm new to fish, but if I understand the definition of __vfsupport_setup_autocomplete correctly, it's supposed to be executed automatically? However, it's not.

I have the following in my config.fish:

```
set tacklebox_modules virtualfish virtualhooks
set tacklebox_plugins docker grc pip python up extract
. ~/.tacklebox/tacklebox.fish
```

The `vf` command is available but pressing Tab anywhere in a `vf` command line gives the following error:

```
fish: Unknown command '__vfcompletion_using_command'
in command substitution
	called on standard input
```

if I manually execute `__vfsupport_setup_autocomplete` in my fish shell, then `vf` completion works.

**Comment by justinmayer** [comment]
Thanks for submitting this issue report, Gordon. I believe I've fixed this problem. Let me know if it persists.

**Comment by doxxx** [comment]
Confirmed, vf completion now works.

**Comment by justinmayer** [comment]
Excellent. Thanks for letting me know, and apologies for the long delay in addressing it.
