### ISSUE TITLE
fish: Unknown command 'grc'

### ISSUE THREAD

**Issue by yeungocanh** [justinmayer/tackle#17]
~ ❯❯❯ df -h
fish: Unknown command 'grc'
~/.tackle/plugins/grc/_colorize.fish (line 2):     grc -es --colour=auto $argv
                                                   ^
in function '_colorize'
	called on line 2 of file ~/.tackle/plugins/grc/df.fish
	with parameter list '--config=conf.df df -h'

http://prntscr.com/9sg5fp

**Comment by justinmayer** [comment]
Did you install `grc` itself? [As noted in the ReadMe](https://github.com/justinmayer/tackle#plugins), that's a prerequisite for that plugin.

**Comment by yeungocanh** [comment]
sorry, i miss read that line 
"grc — colorizes terminal output of ping, make, and other commands (must first install grc via Homebrew/apt)"
